# _config.yml
theme: minima
title: 4devs2k
description: Developer Community
url: "https://4devs2k.github.io"
baseurl: ""

# Wichtige Includes
include:
  - _includes # F端r Hauptinhalte
  - _sass # F端r SCSS/CSS
  - assets # F端r Fonts, Bilder, CSS/JS

# Sass-Konfiguration
sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - _sass

# Plugin-Sicherheit (f端r GitHub Pages)
plugins:
  - jekyll-sass-converter
  - jekyll-include-cache

# Weitere Einstellungen
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
